#creates a workflow that lint, test, and build
name: Python workflow

on:
  push:
    paths:
      - 'services/cities/**'


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        working-directory: ./services/cities
        run: pip install --no-cache -r requirements.txt

      - name: Flake8
        working-directory: ./services/cities
        run: flake8 *.py

      - name: Black
        working-directory: ./services/cities
        run: black --check *.py

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        working-directory: ./services/cities
        run: pip install --no-cache -r requirements.txt

      - name: Run tests
        working-directory: ./services/cities
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: install deps
        working-directory: ./services/cities
        run: echo "Build"




